name: dotnet

on: [push]

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: LD_DEBUG=libs dotnet run
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: dotnet build
      - run: cp pr-libshaderc_shared.so bin/Debug/net8.0/runtimes/linux-x64/native/libshaderc_shared.so
      - run: LD_DEBUG=libs dotnet run
  spirzza:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: dotnet build
      - run: cp spirzza-libshaderc_shared.so bin/Debug/net8.0/runtimes/linux-x64/native/libshaderc_shared.so
      - run: LD_DEBUG=libs dotnet run